#!/bin/bash
#SBATCH --job-name=recipe_official
#SBATCH --partition=longgpu
#SBATCH --gres=gpu:a10080gb:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=4-00:00:00
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --exclude=gruenau9

# ==============================================================================
# RECIPE Baseline — Official Repo (https://github.com/qizhou000/RECIPE)
#
# Runs the EMNLP-2024 author implementation adapted to Mistral-7B-Instruct-v0.3
# and SituatedQA edit-pairs. This replaces our custom reimplementation.
#
# Setup performed in advance:
#   - external/RECIPE/utils/global_attrs.py       -> absolute paths
#   - external/RECIPE/configs/recipe/mistral-7b.yaml
#   - external/RECIPE/utils/utils.py              -> mistral-7b dispatch
#   - external/RECIPE/data/meta-train/zsre/zsre_mend_train.json
#     (generated by scripts/convert_edit_pairs_to_zsre.py from data/edit_pairs.json)
#
# Notes:
#   - Official training runs 1000 epochs over the full meta-train set.
#     Pass fewer via an override if wall-time is tight (edit train_recipe.py
#     or wrap it).
#   - int4/int8 quantization is not supported — the prompt injection hook
#     requires gradients through inputs_embeds. The model is loaded in the
#     default precision (fp16 on A100 is fine; Mistral's native dtype is
#     bfloat16 via device_map).
# ==============================================================================

set -euo pipefail

cd "${SLURM_SUBMIT_DIR}"

CONDA_BASE=/usr/local/anaconda3-2024.06
source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda activate pnr

export TQDM_MININTERVAL=10
export TQDM_NCOLS=100

echo "======================================================================"
echo "Job ID       : ${SLURM_JOB_ID}"
echo "Node         : ${SLURMD_NODENAME}"
echo "Started      : $(date)"
echo "======================================================================"

# Regenerate ZSRE-formatted training data from edit_pairs.json
python scripts/convert_edit_pairs_to_zsre.py

# Official repo uses relative paths — run from its root
cd external/RECIPE
python train_recipe.py -mn mistral-7b -dn zsre "$@"

echo "======================================================================"
echo "Finished : $(date)"
echo "======================================================================"
