"""
System 4a — Self-Generated Rehearsal ("Dreaming")
===================================================

The stable core + frozen experts generate synthetic examples representative
of previously learned distributions. These aren't stored data — they're
sampled from the model's own learned distribution.

Safeguards against model collapse (Shumailov et al.):
1. Distributional anchoring via statistical fingerprints
2. System 5 as fact-checker (knowledge store veto)
3. Logarithmic frozen reference schedule with KL divergence checks
4. Diversity-enforcing generation (high temperature, nucleus sampling,
   forced tail coverage)

Additionally (accepting the information-theoretic barrier):
5. Coreset-based real data anchoring (0.01-0.1% of historical data)
6. Learned distributional discriminator
7. Periodic external grounding

The honest assessment: self-rehearsal maintains high fidelity on the core
of distributions for hundreds of consolidation cycles, but distributional
tails degrade over unbounded time without real data anchoring.
"""

from __future__ import annotations

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import torch
from transformers import PreTrainedModel, PreTrainedTokenizerBase

from .config import ConsolidationConfig

logger = logging.getLogger(__name__)


@dataclass
class RehearsalSample:
    """A single sample generated by self-rehearsal."""
    text: str
    source_expert: str
    generation_temperature: float
    timestamp: float = field(default_factory=time.time)
    passed_fingerprint_check: bool = True
    passed_fact_check: bool = True
    discriminator_score: float = 1.0


@dataclass
class DistributionalFingerprint:
    """Lightweight statistical fingerprint of a data distribution.

    Captures first and second moments of embedding distributions
    for each expert's training data. Used as a fast check during
    rehearsal to detect distributional drift.
    """
    expert_id: str
    mean: np.ndarray
    std: np.ndarray
    n_samples: int = 0
    timestamp: float = field(default_factory=time.time)

    def check_sample(
        self,
        embedding: np.ndarray,
        threshold: float = 3.0,
    ) -> bool:
        """Check if a sample embedding is within the distribution.

        Uses a z-score threshold on the per-dimension deviations.
        """
        z_scores = np.abs((embedding - self.mean) / (self.std + 1e-8))
        fraction_extreme = (z_scores > threshold).mean()
        return fraction_extreme < 0.3


class FrozenReferenceManager:
    """Manages a logarithmic schedule of frozen reference generators.

    Maintains checkpoints from 1, 2, 4, 8, 16, ... consolidation cycles
    ago. Checks rehearsal consistency against multiple timescales to detect
    and correct drift before it compounds.

    Storage cost: O(log T) for T cycles.
    """

    def __init__(self, max_references: int = 10) -> None:
        self._references: dict[int, str] = {}
        self._current_cycle: int = 0
        self._max_references = max_references

    @property
    def reference_cycles(self) -> list[int]:
        return sorted(self._references.keys())

    def should_save_reference(self, cycle: int) -> bool:
        """Determine if this cycle should be saved as a frozen reference.

        Uses a logarithmic schedule: save at cycles that are powers of 2
        back from the current cycle.
        """
        if cycle <= 0:
            return True

        # Keep references at logarithmic intervals
        for exp in range(0, 20):
            target = cycle - (1 << exp)
            if target >= 0 and target not in self._references:
                return True

        return len(self._references) < self._max_references

    def register_reference(self, cycle: int, checkpoint_path: str) -> None:
        """Register a frozen reference checkpoint."""
        self._references[cycle] = checkpoint_path
        self._current_cycle = max(self._current_cycle, cycle)

        # Prune old references to maintain logarithmic coverage
        if len(self._references) > self._max_references:
            self._prune_references()

        logger.info(
            f"Frozen reference registered: cycle {cycle} "
            f"(total: {len(self._references)})"
        )

    def _prune_references(self) -> None:
        """Prune references to maintain logarithmic spacing."""
        if len(self._references) <= self._max_references:
            return

        cycles = sorted(self._references.keys())

        # Always keep first and last
        keep = {cycles[0], cycles[-1]}

        # Keep logarithmic spacing from current
        for exp in range(0, 20):
            target = self._current_cycle - (1 << exp)
            # Find closest existing reference
            closest = min(cycles, key=lambda c: abs(c - target))
            keep.add(closest)
            if len(keep) >= self._max_references:
                break

        to_remove = [c for c in cycles if c not in keep]
        for c in to_remove:
            del self._references[c]

    def get_reference_path(self, cycle: int) -> str | None:
        return self._references.get(cycle)


class Coreset:
    """Minimal real data anchor for preventing unbounded model collapse.

    Stores a carefully selected, maximally informative subset of real
    training data (0.01-0.1% of historical data). Provides a
    distributional anchor that no amount of self-rehearsal safeguards
    can match for distributional tails.
    """

    def __init__(
        self,
        max_samples: int = 5000,
        selection_method: str = "facility_location",
    ) -> None:
        self._samples: list[dict[str, Any]] = []
        self._embeddings: np.ndarray | None = None
        self._max_samples = max_samples
        self._selection_method = selection_method

    @property
    def size(self) -> int:
        return len(self._samples)

    def add_samples(
        self,
        samples: list[dict[str, Any]],
        embeddings: np.ndarray | None = None,
    ) -> int:
        """Add samples to the coreset with diversity-based selection.

        If adding would exceed max capacity, selects the most diverse
        subset using k-center greedy (approximates facility location).
        """
        if not samples:
            return 0

        self._samples.extend(samples)

        if embeddings is not None:
            if self._embeddings is None:
                self._embeddings = embeddings
            else:
                self._embeddings = np.vstack([self._embeddings, embeddings])

        if len(self._samples) > self._max_samples:
            self._select_diverse_subset()

        return len(self._samples)

    def _select_diverse_subset(self) -> None:
        """Select a diverse subset using k-center greedy algorithm."""
        if self._embeddings is None or len(self._embeddings) < self._max_samples:
            self._samples = self._samples[:self._max_samples]
            return

        n = len(self._embeddings)
        selected = [0]
        min_distances = np.full(n, np.inf)

        for _ in range(self._max_samples - 1):
            last = selected[-1]
            dists = np.linalg.norm(
                self._embeddings - self._embeddings[last], axis=1,
            )
            min_distances = np.minimum(min_distances, dists)
            min_distances[selected] = -1
            next_idx = int(np.argmax(min_distances))
            selected.append(next_idx)

        self._samples = [self._samples[i] for i in selected]
        self._embeddings = self._embeddings[selected]

    def get_samples(self, n: int | None = None) -> list[dict[str, Any]]:
        """Get coreset samples for rehearsal anchoring."""
        if n is None:
            return list(self._samples)
        indices = np.random.choice(
            len(self._samples), size=min(n, len(self._samples)), replace=False,
        )
        return [self._samples[i] for i in indices]


class RehearsalEngine:
    """Orchestrates self-generated rehearsal with collapse safeguards.

    Generates synthetic training data from frozen experts and the stable
    core, applying multi-layered safeguards to prevent model collapse:
    distributional fingerprints, fact-checking, frozen references,
    and diversity enforcement.
    """

    def __init__(self, config: ConsolidationConfig | None = None) -> None:
        self.config = config or ConsolidationConfig()

        self._fingerprints: dict[str, DistributionalFingerprint] = {}
        self._frozen_refs = FrozenReferenceManager(
            max_references=self.config.max_frozen_references,
        )
        self._coreset = Coreset(
            max_samples=self.config.coreset_max_samples,
            selection_method=self.config.coreset_selection,
        )
        self._total_generated: int = 0

        logger.info("RehearsalEngine initialized")

    # ------------------------------------------------------------------
    # Fingerprint management
    # ------------------------------------------------------------------

    def register_fingerprint(
        self,
        expert_id: str,
        embeddings: np.ndarray,
    ) -> DistributionalFingerprint:
        """Register a distributional fingerprint for an expert."""
        fp = DistributionalFingerprint(
            expert_id=expert_id,
            mean=embeddings.mean(axis=0),
            std=embeddings.std(axis=0),
            n_samples=len(embeddings),
        )
        self._fingerprints[expert_id] = fp
        return fp

    # ------------------------------------------------------------------
    # Generation
    # ------------------------------------------------------------------

    def generate_rehearsal(
        self,
        model: PreTrainedModel,
        tokenizer: PreTrainedTokenizerBase,
        expert_id: str,
        prompts: list[str],
        knowledge_facts: list[str] | None = None,
    ) -> list[RehearsalSample]:
        """Generate rehearsal samples from a frozen expert.

        Applies diversity-enforcing generation with high temperature
        and nucleus sampling, then filters through distributional
        fingerprint and fact-checking.

        Args:
            model: The model with the frozen expert loaded.
            tokenizer: Tokenizer for generation.
            expert_id: Which expert is generating.
            prompts: Seed prompts for generation.
            knowledge_facts: Facts from System 5 for verification.

        Returns:
            List of verified rehearsal samples.
        """
        samples = []
        fingerprint = self._fingerprints.get(expert_id)

        model.eval()
        with torch.no_grad():
            for prompt in prompts:
                inputs = tokenizer(
                    prompt,
                    return_tensors="pt",
                    truncation=True,
                    max_length=512,
                )
                inputs = {k: v.to(model.device) for k, v in inputs.items()}

                outputs = model.generate(
                    **inputs,
                    max_new_tokens=self.config.rehearsal_max_tokens,
                    temperature=self.config.rehearsal_temperature,
                    top_p=self.config.rehearsal_top_p,
                    min_p=self.config.tail_coverage_min_p,
                    do_sample=True,
                    pad_token_id=tokenizer.pad_token_id,
                )

                prompt_len = inputs["input_ids"].shape[1]
                generated_ids = outputs[0][prompt_len:]
                text = tokenizer.decode(generated_ids, skip_special_tokens=True)

                sample = RehearsalSample(
                    text=text,
                    source_expert=expert_id,
                    generation_temperature=self.config.rehearsal_temperature,
                )

                samples.append(sample)
                self._total_generated += 1

        logger.info(
            f"Generated {len(samples)} rehearsal samples "
            f"from expert '{expert_id}'"
        )
        return samples

    # ------------------------------------------------------------------
    # Coreset management
    # ------------------------------------------------------------------

    def add_to_coreset(
        self,
        samples: list[dict[str, Any]],
        embeddings: np.ndarray | None = None,
    ) -> int:
        """Add real data samples to the coreset anchor."""
        return self._coreset.add_samples(samples, embeddings)

    def get_coreset_samples(self, n: int | None = None) -> list[dict[str, Any]]:
        return self._coreset.get_samples(n)

    # ------------------------------------------------------------------
    # Interleaved data mixing
    # ------------------------------------------------------------------

    def create_interleaved_batch(
        self,
        buffer_samples: list[str],
        rehearsal_ratio: float | None = None,
        model: PreTrainedModel | None = None,
        tokenizer: PreTrainedTokenizerBase | None = None,
        expert_id: str = "",
        prompts: list[str] | None = None,
    ) -> list[str]:
        """Create an interleaved batch of buffer + rehearsal data.

        The mixing ratio alpha_t controls the proportion:
        batch = alpha_t * buffer_samples + (1 - alpha_t) * rehearsed_samples

        Because LLM inputs are discrete tokens, interpolation happens at
        the data-stream level (which samples to include), not at token level.

        Args:
            buffer_samples: New data from the fast buffer.
            rehearsal_ratio: Fraction of rehearsal data (overrides default).
            model: Model for generating rehearsal (if no cached samples).
            tokenizer: Tokenizer for generation.
            expert_id: Expert to generate from.
            prompts: Seed prompts for rehearsal generation.

        Returns:
            Mixed batch of texts for training.
        """
        ratio = rehearsal_ratio or self.config.default_rehearsal_ratio

        n_total = len(buffer_samples)
        n_rehearsal = int(n_total * ratio / (1.0 - ratio + 1e-8))
        n_rehearsal = min(n_rehearsal, n_total * 2)

        # Get rehearsal samples (from coreset if available)
        rehearsal_texts = []
        coreset = self._coreset.get_samples(n_rehearsal)
        if coreset:
            rehearsal_texts = [
                s.get("text", s.get("question", "")) for s in coreset
            ]

        # If not enough coreset samples and model available, generate
        if len(rehearsal_texts) < n_rehearsal and model and tokenizer and prompts:
            needed = n_rehearsal - len(rehearsal_texts)
            gen_prompts = prompts[:needed]
            generated = self.generate_rehearsal(
                model, tokenizer, expert_id, gen_prompts,
            )
            rehearsal_texts.extend([s.text for s in generated])

        # Interleave
        combined = list(buffer_samples) + rehearsal_texts[:n_rehearsal]
        rng = np.random.RandomState(42)
        rng.shuffle(combined)

        return combined

    def summary(self) -> str:
        return (
            f"RehearsalEngine: {self._total_generated} total generated, "
            f"coreset={self._coreset.size}, "
            f"fingerprints={len(self._fingerprints)}, "
            f"frozen_refs={len(self._frozen_refs.reference_cycles)}"
        )
